#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import ti
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

# for c in range(1,5):
#     M = round(0.2*c, 1)

lattice = ti.Lattice(
PBC_i = False,
PBC_j = False,
Corners = True,
alpha = 0,
hal = 0,
M=0,
N=7)

lattice.large_alpha = True
lattice.large_hal = True

lattice.initialize_hamiltonian()
print(ti.zero_eig(lattice.h))
# lattice.phase_diagram(s=50,t=50)
# lattice.single_state()
# lattice.plot_groundstate()
lattice.phase_diagram()
