#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import ti
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

lattice = ti.Lattice(
PBC_i = True,
PBC_j = True,
Corners = False,
alpha = 0.1,
hal = 0.4,
M=0,
N=7)

lattice.large_alpha = False
lattice.large_hal = False

#lattice.phase_diagram(s=50,t=50)
lattice.energy_spectrum('Alpha',lattice.hal)
#lattice.plot_groundstate()
#lattice.energy_spectrum_full(indep = "Lambda", set_val = 0, t = 1000)
